name: apex_api
description: Apex Flutter Connection Api
version: 1.0.1
homepage: https://gitlab.com/1839491/apex_api.git
publish_to: https://pub.dev

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^3.6.2
  encrypt: ^5.0.1
  crypto: ^3.0.2
  http: ^0.13.4
  http_parser: ^4.0.1
  socket_io_client: ^1.0.2
  shared_preferences: ^2.0.15
  timezone: ^0.8.0
  fingerprintjs: ^2.0.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  platform_device_id: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
