name: apex_api
description: Apex Flutter Connection Api
version: 2.0.7
homepage: https://gitlab.com/1839491/apex_api.git

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^3.7.3
  encrypt: ^5.0.1
  crypto: ^3.0.2
  http: ^0.13.5
  http_parser: ^4.0.1
  socket_io_client: ^1.0.2
  shared_preferences: ^2.0.15
  timezone: ^0.9.0
  fingerprintjs: ^2.0.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  device_info_plus: ^9.0.0
  universal_html: ^2.0.8
  logger: ^1.1.0
  provider: ^6.0.5
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.1
  cancellation_token: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
